# Generated by Django 4.0.8 on 2023-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='phone', max_length=120),
            preserve_default=False,
        ),
    ]
